export const BankCode = {
    VIB: "VIB",
    ABB: "ABB",
    ACB: "ACB",
    BAB: "BAB",
    BIDV: "BIDV",
    BVB: "BVB",
    CBB: "CBB",
    CCF: "CCF",
    CIMB: "CIMB",
    DBS: "DBS",
    DOB: "DOB",
    EIB: "EIB",
    GPB: "GPB",
    HDB: "HDB",
    HLBVN: "HLBVN",
    HSBC: "HSBC",
    IBKHN: "IBK HN",
    IBKHCM: "IBK HCM",
    ICB: "ICB",
    IVB: "IVB",
    KBHN: "KB HN",
    KBHCM: "KB HCM",
    KLB: "KLB",
    LPB: "LPB",
    MB: "MB",
    MSB: "MSB",
    NAB: "NAB",
    NCB: "NCB",
    NHBHN: "NHB HN",
    OCB: "OCB",
    OCEANBANK: "OCEANBANK",
    PBVN: "PBVN",
    PGB: "PGB",
    PVCB: "PVCB",
    SCB: "SCB",
    SCVN: "SCVN",
    SEAB: "SEAB",
    SGICB: "SGICB",
    SHB: "SHB",
    STB: "STB",
    SHBVN: "SHBVN",
    TCB: "TCB",
    TPB: "TPB",
    UOB: "UOB",
    VAB: "VAB",
    VBA: "VBA",
    VCB: "VCB",
    VCCB: "VCCB",
    VIETBANK: "VIETBANK",
    VPB: "VPB",
    CAKE: "CAKE",
    UBANK: "UBANK",
    VRB: "VRB",
    WVN: "WVN",
    KBANK: "KBANK"
}


